version: '3.8'

services:
  mrrobot_trade:
    build: .
    container_name: mrrobot_trade_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./src:/app/src  # Hot reload for development (optional but useful)
    logging:
      driver: "json-file"
      options:
        max-size: "10m"      # Maximum size of each log file
        max-file: "3"        # Keep only 3 rotated log files
        compress: "true"     # Compress rotated logs
